# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: myworld.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='myworld.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rmyworld.proto\"\x1b\n\x0bSomeRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1c\n\tSomeReply\x12\x0f\n\x07message\x18\x01 \x01(\t26\n\tMyGreeter\x12)\n\x0b\x44oSomething\x12\x0c.SomeRequest\x1a\n.SomeReply\"\x00\x62\x06proto3'
)




_SOMEREQUEST = _descriptor.Descriptor(
  name='SomeRequest',
  full_name='SomeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='SomeRequest.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=44,
)


_SOMEREPLY = _descriptor.Descriptor(
  name='SomeReply',
  full_name='SomeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='SomeReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=74,
)

DESCRIPTOR.message_types_by_name['SomeRequest'] = _SOMEREQUEST
DESCRIPTOR.message_types_by_name['SomeReply'] = _SOMEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SomeRequest = _reflection.GeneratedProtocolMessageType('SomeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SOMEREQUEST,
  '__module__' : 'myworld_pb2'
  # @@protoc_insertion_point(class_scope:SomeRequest)
  })
_sym_db.RegisterMessage(SomeRequest)

SomeReply = _reflection.GeneratedProtocolMessageType('SomeReply', (_message.Message,), {
  'DESCRIPTOR' : _SOMEREPLY,
  '__module__' : 'myworld_pb2'
  # @@protoc_insertion_point(class_scope:SomeReply)
  })
_sym_db.RegisterMessage(SomeReply)



_MYGREETER = _descriptor.ServiceDescriptor(
  name='MyGreeter',
  full_name='MyGreeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=76,
  serialized_end=130,
  methods=[
  _descriptor.MethodDescriptor(
    name='DoSomething',
    full_name='MyGreeter.DoSomething',
    index=0,
    containing_service=None,
    input_type=_SOMEREQUEST,
    output_type=_SOMEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MYGREETER)

DESCRIPTOR.services_by_name['MyGreeter'] = _MYGREETER

# @@protoc_insertion_point(module_scope)
